#!/usr/bin/env sh
# Compare the multi-index AND-intersect query: VertexDB (intersect) vs Postgres
# BitmapAnd / Bitmap Heap Scan.
#
# Usage:
#   scripts/compare_bitmap_and.sh
#   ROWS=10000 CLI=./build/VertexDB_cli scripts/compare_bitmap_and.sh
#
# Requires: VertexDB_cli (build first). Postgres half needs Docker with a working daemon
# (or PGHOST/PGUSER/PGDATABASE pointing at an existing server with psql on PATH).

set -eu

ROOT="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
ROWS="${ROWS:-10000}"
CLI="${CLI:-$ROOT/build/VertexDB_cli}"
PG_IMAGE="${PG_IMAGE:-postgres:16}"
CONTAINER="${CONTAINER:-vertexdb-intersect-pg}"
PG_PORT="${PG_PORT:-55433}"
OUT="${OUT:-}"
KEEP_CONTAINER="${KEEP_CONTAINER:-0}"

win_sql_pg() {
    cat <<'SQL'
EXPLAIN (COSTS OFF)
SELECT name FROM employees WHERE dept = 1 AND city = 1;
SQL
}

seed_pg_sql() {
    cat <<SQL
DROP TABLE IF EXISTS employees;
CREATE TABLE employees (
  id integer PRIMARY KEY,
  dept integer NOT NULL,
  city integer NOT NULL,
  name text NOT NULL
);
INSERT INTO employees (id, dept, city, name)
SELECT g, g % 10, (g / 10) % 10, 'Emp' || g
FROM generate_series(1, ${ROWS}) AS g;
CREATE INDEX employees_dept_idx ON employees (dept);
CREATE INDEX employees_city_idx ON employees (city);
ANALYZE employees;
SQL
}

section() {
    printf '\n## %s\n\n' "$1"
}

have_docker_postgres() {
    command -v docker >/dev/null 2>&1 || return 1
    docker info >/dev/null 2>&1 || return 1
    return 0
}

have_local_psql() {
    command -v psql >/dev/null 2>&1 || return 1
    psql -c 'SELECT 1' >/dev/null 2>&1 || return 1
    return 0
}

run_vertexdb() {
    section "VertexDB (multi-index intersect)"

    if [ ! -x "$CLI" ]; then
        echo "VertexDB CLI not found at $CLI"
        echo "Build with: cmake -S . -B build && cmake --build build --target VertexDB_cli"
        return 1
    fi

    work="$(mktemp -d "${TMPDIR:-/tmp}/vertexdb-intersect-cmp.XXXXXX")"
    cleanup_vd() { rm -rf "$work"; }
    trap cleanup_vd EXIT

    {
        echo 'CREATE DATABASE intersect_cmp;'
        echo 'CREATE TABLE Employees (id INT, dept INT, city INT, name STRING);'
        echo 'CREATE INDEX idx_dept ON Employees(dept);'
        echo 'CREATE INDEX idx_city ON Employees(city);'
        echo 'INSERT INTO Employees VALUES (1, 1, 0, "a"), (11, 1, 1, "b"), (21, 1, 2, "c"), (111, 1, 1, "d");'
        echo 'EXPLAIN SELECT name FROM Employees WHERE dept = 1 AND city = 1;'
        echo 'SELECT name FROM Employees WHERE dept = 1 AND city = 1 ORDER BY id;'
        echo 'EXIT;'
    } >"$work/seed.sql"

    echo "CLI: $CLI"
    echo 'Query: SELECT name FROM Employees WHERE dept = 1 AND city = 1;'
    echo
    echo '```text'
    (cd "$work" && "$CLI" <"$work/seed.sql") | sed -n '/^plan/,/^VertexDB> selected/p' | sed '/^VertexDB> selected/d'
    echo '```'
    echo
    echo 'Expected: multi-index intersect on `dept`, `city`.'
    echo "For 1k/100k timings see \`BM_MultiIndexIntersectSelect\` vs \`BM_SingleIndexResidualSelect\`."

    trap - EXIT
    cleanup_vd
}

start_docker_pg() {
    docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
    docker run -d --name "$CONTAINER" \
        -e POSTGRES_PASSWORD=postgres \
        -e POSTGRES_USER=postgres \
        -e POSTGRES_DB=intersect_cmp \
        -p "${PG_PORT}:5432" \
        "$PG_IMAGE" >/dev/null

    i=0
    while [ "$i" -lt 60 ]; do
        if docker exec "$CONTAINER" pg_isready -U postgres >/dev/null 2>&1; then
            return 0
        fi
        i=$((i + 1))
        sleep 1
    done
    echo "Postgres container did not become ready" >&2
    return 1
}

run_postgres_docker() {
    section "Postgres via Docker (${PG_IMAGE}, ${ROWS} rows)"

    start_docker_pg
    docker exec -i "$CONTAINER" psql -U postgres -d intersect_cmp -v ON_ERROR_STOP=1 <<<"$(seed_pg_sql)" >/dev/null

    echo '### EXPLAIN'
    echo
    echo '```text'
    docker exec -i "$CONTAINER" psql -U postgres -d intersect_cmp -v ON_ERROR_STOP=1 <<<"$(win_sql_pg)"
    echo '```'
    echo
    echo 'Look for: BitmapAnd of two Bitmap Index Scans (or equivalent bitmap/index combination),'
    echo 'not a single index probe with the other equality applied only as a Filter on a huge heap walk.'

    if [ "$KEEP_CONTAINER" != 1 ]; then
        docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
    else
        echo "Left container running: $CONTAINER (port $PG_PORT)"
    fi
}

run_postgres_local() {
    section "Postgres via local psql (${ROWS} rows)"

    psql -v ON_ERROR_STOP=1 <<<"$(seed_pg_sql)" >/dev/null

    echo '### EXPLAIN'
    echo
    echo '```text'
    psql -v ON_ERROR_STOP=1 <<<"$(win_sql_pg)"
    echo '```'
}

main() {
    report="$(mktemp "${TMPDIR:-/tmp}/vertexdb-intersect-report.XXXXXX.md")"
    {
        echo '# BitmapAnd parity comparison'
        echo
        echo "Generated by \`scripts/compare_bitmap_and.sh\` (ROWS=${ROWS})."
        echo
        echo 'Win query:'
        echo
        echo '```sql'
        echo 'SELECT name FROM Employees WHERE dept = 1 AND city = 1;'
        echo '```'

        run_vertexdb

        if have_docker_postgres; then
            run_postgres_docker
        elif have_local_psql; then
            run_postgres_local
        else
            section "Postgres (skipped)"
            echo 'Neither Docker (daemon up) nor a working local `psql` was available.'
            echo 'Start Docker Desktop (or set PG* + install psql), then re-run this script.'
            echo 'Illustrative BitmapAnd plan shapes are in docs/bitmap_and_comparison.md.'
        fi
    } >"$report"

    if [ -n "$OUT" ]; then
        cp "$report" "$OUT"
        echo "Wrote $OUT"
    fi
    cat "$report"
    rm -f "$report"
}

main "$@"
